name: mlops-project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - pandas==2.1.4
    - "numpy>=1.26.2,<2.0.0"
    - scikit-learn==1.3.2
    - matplotlib==3.8.2
    - seaborn==0.13.0
    - mlflow==2.9.2
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - pydantic==2.5.2
    - pydantic-settings==2.1.0
    - pytest==7.4.3
    - pytest-cov==4.1.0
    - pytest-mock==3.12.0
    - black==23.11.0
    - flake8==6.1.0
    - pylint==3.0.2
    - prometheus-client==0.19.0
    - requests==2.31.0
    - jupyter==1.0.0
    - notebook==7.0.6
    - ipykernel==6.26.0
    - python-dotenv==1.0.0
    - "joblib>=1.3.0"
    - "protobuf>=4.25.0,<6.0.0"
